# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-foreach" do
  desc "Utility to recursively run commands in Git repositories."
  homepage ""
  version "0.4.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-foreach"

  on_macos do
    on_intel do
      url "https://github.com/marcfrederick/git-foreach/releases/download/v0.4.4/git-foreach_0.4.4_darwin_amd64.tar.gz"
      sha256 "259a73ba43961b335f75fae50f6b91a61364e6d5359e29f29e05da62ad481eba"
    end
    on_arm do
      url "https://github.com/marcfrederick/git-foreach/releases/download/v0.4.4/git-foreach_0.4.4_darwin_arm64.tar.gz"
      sha256 "e66357e5855523fd8e5b65d785c404c5e35423fc5df234564552908b4f8dc0e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcfrederick/git-foreach/releases/download/v0.4.4/git-foreach_0.4.4_linux_amd64.tar.gz"
      sha256 "478af07975ef887bd436e1ac51bb513f444b81a2df3363200c471bd0b7792f90"
    end
    on_arm do
      url "https://github.com/marcfrederick/git-foreach/releases/download/v0.4.4/git-foreach_0.4.4_linux_arm64.tar.gz"
      sha256 "768b5896061c7f2709f7770c1a0b08562f4343f870fb2c1c2b8b99cd04b44157"
    end
  end

  # No zap stanza required
end
