# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-foreach" do
  desc "Utility to recursively run commands in Git repositories."
  homepage ""
  version "0.4.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-foreach"

  on_macos do
    on_intel do
      url "https://github.com/marcfrederick/git-foreach/releases/download/v0.4.5/git-foreach_0.4.5_darwin_amd64.tar.gz"
      sha256 "0978d2bb431f21ec55053f4b4f3c05e3b5d58c20c8d4c206e64f9f24ca0b7c0c"
    end
    on_arm do
      url "https://github.com/marcfrederick/git-foreach/releases/download/v0.4.5/git-foreach_0.4.5_darwin_arm64.tar.gz"
      sha256 "3b197491c3b7891d6ad4ecac88e01246c966dbfee3a91a13cfaec7a8bde0c814"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcfrederick/git-foreach/releases/download/v0.4.5/git-foreach_0.4.5_linux_amd64.tar.gz"
      sha256 "c93f4285b2ede5f7feb28e08bbb33dd987fe8fde9d5c3d1d66eac482db86006c"
    end
    on_arm do
      url "https://github.com/marcfrederick/git-foreach/releases/download/v0.4.5/git-foreach_0.4.5_linux_arm64.tar.gz"
      sha256 "9cdfc5dad266965038f7674a70abdfed374f922db33e10942f054d2a86da5a2a"
    end
  end

  # No zap stanza required
end
