# This file was generated by GoReleaser. DO NOT EDIT.
cask "imaginary-exporter" do
  name "imaginary-exporter"
  desc "Prometheus exporter for Imaginary"
  homepage ""
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imaginary-exporter"

  on_macos do
    on_intel do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v#{version}/imaginary-exporter_Darwin_x86_64.tar.gz"
      sha256 "4d688eabef4c755161cb58ac8223e4fa8555bf71ca2ce2ac151a986d68cae763"
    end
    on_arm do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v#{version}/imaginary-exporter_Darwin_arm64.tar.gz"
      sha256 "5126a0c14b3465a7b764dd6905c21cd763414ca62d9a39f14b0a74232abc27b0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v#{version}/imaginary-exporter_Linux_x86_64.tar.gz"
      sha256 "6125b002189f0bfa212ba0755f4c53309d5c1982eded061491b6af3e20bca192"
    end
    on_arm do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v#{version}/imaginary-exporter_Linux_arm64.tar.gz"
      sha256 "58b6c91ce804e89c2328e435335bbdbf54cc2605259a78d81399f4623646cf98"
    end
  end

  # No zap stanza required
end
