# This file was generated by GoReleaser. DO NOT EDIT.
cask "imaginary-exporter" do
  desc "Prometheus exporter for Imaginary"
  homepage ""
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imaginary-exporter"

  on_macos do
    on_intel do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v0.2.2/imaginary-exporter_Darwin_x86_64.tar.gz"
      sha256 "1ea1b16a6c6ac7585039058f50b300d877a23a2218d87d95779ca6ec404c2edd"
    end
    on_arm do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v0.2.2/imaginary-exporter_Darwin_arm64.tar.gz"
      sha256 "f66c5e192b3ffd773eb2b47f2039b8cf543548029d07baf16d916757cc7cb5f4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v0.2.2/imaginary-exporter_Linux_x86_64.tar.gz"
      sha256 "b242f53278443124abccbe533ec33165beec1212cbb9d372e0ce2f67b8d35d65"
    end
    on_arm do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v0.2.2/imaginary-exporter_Linux_arm64.tar.gz"
      sha256 "584fd516e576761a432b485360c0dc91691576c2b1f7827fafe1add638c8901c"
    end
  end

  # No zap stanza required
end
