# This file was generated by GoReleaser. DO NOT EDIT.
cask "imaginary-exporter" do
  desc "Prometheus exporter for Imaginary"
  homepage ""
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imaginary-exporter"

  on_macos do
    on_intel do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v0.2.3/imaginary-exporter_Darwin_x86_64.tar.gz"
      sha256 "994473eb0504aaa2dec84d662f77a29679a24d9254a9a86f059b001a1e7ecd84"
    end
    on_arm do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v0.2.3/imaginary-exporter_Darwin_arm64.tar.gz"
      sha256 "8d8697f81f87fd6c7e368bb635f8251dca05e2dd9be5db508c9345b363fa48c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v0.2.3/imaginary-exporter_Linux_x86_64.tar.gz"
      sha256 "b6aec9dd0c55fe3217df3979bb9d30d5c3a578bf186a6c4d096cc2489c491dc7"
    end
    on_arm do
      url "https://github.com/marcfrederick/imaginary-exporter/releases/download/v0.2.3/imaginary-exporter_Linux_arm64.tar.gz"
      sha256 "52aeb0d04643efc43230fa8ea55d78395297cd835ba8edf83acb0f088ecfd49c"
    end
  end

  # No zap stanza required
end
