# This file was generated by GoReleaser. DO NOT EDIT.
cask "tofu-target-file" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "09d4c016a0190e02701a287ff8b123081a6ee74cd98868f1d330ee3cd6825f6f"
      url "https://github.com/marcfrederick/tofu-target-file/releases/download/v#{version}/tofu-target-file_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "761b965b845c8975ff2ba412aa2bf62ee204bc334fe49e71e966197bdbc50ecd"
      url "https://github.com/marcfrederick/tofu-target-file/releases/download/v#{version}/tofu-target-file_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb0fe48a36f2a9ad565043427a02b005941898de8e6610bbc544997b1bcca364"
      url "https://github.com/marcfrederick/tofu-target-file/releases/download/v#{version}/tofu-target-file_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b0701ef75bdbf198252ccbdc8e79981ff125317c992e460e5b00f9f3f2bb4ab3"
      url "https://github.com/marcfrederick/tofu-target-file/releases/download/v#{version}/tofu-target-file_Linux_arm64.tar.gz"
    end
  end

  name "tofu-target-file"
  desc "A tool to generate a target file for Tofu"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tofu-target-file"

  # No zap stanza required

end
